In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IMDB Dataset.csv')

In [3]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
#lowercasing
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [5]:
df['review']=df['review'].str.lower()

In [6]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [7]:
#removing html tags
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [8]:
df['review']=df['review'].apply(remove_html_tags)

In [9]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [10]:
#correcting spelling
!pip install textblob
from textblob import TextBlob


[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
incorrect_text = "hello whatt a wondefull eveningg"
textBlb = TextBlob(incorrect_text)
textBlb.correct().string


'hello what a wonderful evening'

In [12]:
!pip install nltk


[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
import nltk
from nltk import downloader

# Disable proxy
nltk.set_proxy('')

# Download stopwords
downloader.download('stopwords')



[nltk_data] Error loading stopwords: <urlopen error no host given>


False

In [29]:
# removing emojis
import re

def remove_emojis(text):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F700-\U0001F77F"  # alchemical symbols
                               u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                               u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                               u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                               u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                               u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                               u"\U00002702-\U000027B0"  # Dingbats
                               u"\U000024C2-\U0001F251" 
                               "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

# Example
text_with_emojis = "Hello! 😊 How are you today? 🌈"
text_without_emojis = remove_emojis(text_with_emojis)

print("Original Text:", text_with_emojis)
print("Text without Emojis:", text_without_emojis)


Original Text: Hello! 😊 How are you today? 🌈
Text without Emojis: Hello!  How are you today? 


In [30]:
#tokenize
from nltk.tokenize import word_tokenize,sent_tokenize

In [36]:
nltk.download('punkt')
import nltk

# Specify NLTK data server (replace 'your_nltk_data_server' with an actual server)
nltk.download('punkt', download_dir='your_nltk_data_server')


[nltk_data] Error loading punkt: <urlopen error no host given>
[nltk_data] Error loading punkt: <urlopen error no host given>


False

In [37]:
import nltk

# Download all NLTK resources
nltk.download('all')

# OR download specific resources
# nltk.download('punkt')
# nltk.download('stopwords')
# ...

# OR download resources from specific NLTK data server
# nltk.download('punkt', download_dir='your_nltk_data_server')


[nltk_data] Error loading all: <urlopen error no host given>


False

In [38]:
#stemming
from nltk.stem.porter import PorterStemmer

In [39]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [40]:
sample = ' walks walk walking walked'
stem_words(sample)

'walk walk walk walk'

In [41]:
#lemmetization
import nltk
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
nltk.download('punkt') 
nltk.download('wordnet')  

def lemmatize_text(text):
    # Tokenize the text
    words = word_tokenize(text)

    # Initialize the WordNet Lemmatizer
    lemmatizer = WordNetLemmatizer()

    # Lemmatize each word in the text
    lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]

    # Join the lemmatized words to form a clean text
    lemmatized_text = ' '.join(lemmatized_words)

    return lemmatized_text

def get_wordnet_pos(word):
    # Map POS tag to first character lemmatize() accepts
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"N": wordnet.NOUN, "V": wordnet.VERB, "R": wordnet.ADV, "J": wordnet.ADJ}
    return tag_dict.get(tag, wordnet.NOUN)

# Example usage
original_text = "The dogs are barking loudly in the garden."
lemmatized_text = lemmatize_text(original_text)

print("Original Text:", original_text)
print("Lemmatized Text:", lemmatized_text)


[nltk_data] Error loading punkt: <urlopen error no host given>
[nltk_data] Error loading wordnet: <urlopen error no host given>


LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/english.pickle

  Searched in:
    - 'C:\\Users\\Shashank Ray/nltk_data'
    - 'C:\\Users\\Shashank Ray\\AppData\\Local\\Programs\\Python\\Python311\\nltk_data'
    - 'C:\\Users\\Shashank Ray\\AppData\\Local\\Programs\\Python\\Python311\\share\\nltk_data'
    - 'C:\\Users\\Shashank Ray\\AppData\\Local\\Programs\\Python\\Python311\\lib\\nltk_data'
    - 'C:\\Users\\Shashank Ray\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - ''
**********************************************************************


In [42]:
#text preprocessing
from sklearn.feature_extraction.text import CountVectorizer

corpus = ["This is a simple example.", "Another example for demonstration."]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Bag-of-Words Matrix:")
print(X.toarray())
print("Feature Names:", vectorizer.get_feature_names())


Bag-of-Words Matrix:
[[0 0 1 0 1 1 1]
 [1 1 1 1 0 0 0]]


AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer_tfidf = TfidfVectorizer()
X_tfidf = vectorizer_tfidf.fit_transform(corpus)

print("TF-IDF Matrix:")
print(X_tfidf.toarray())
print("Feature Names:", vectorizer_tfidf.get_feature_names())


TF-IDF Matrix:
[[0.         0.         0.37997836 0.         0.53404633 0.53404633
  0.53404633]
 [0.53404633 0.53404633 0.37997836 0.53404633 0.         0.
  0.        ]]


AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ["This is a simple example.", "Another example for demonstration."]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Bag-of-Words Matrix:")
print(X.toarray())
print("Feature Names:", vectorizer.get_feature_names_out())

Bag-of-Words Matrix:
[[0 0 1 0 1 1 1]
 [1 1 1 1 0 0 0]]
Feature Names: ['another' 'demonstration' 'example' 'for' 'is' 'simple' 'this']


In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer_tfidf = TfidfVectorizer()
X_tfidf = vectorizer_tfidf.fit_transform(corpus)

print("TF-IDF Matrix:")
print(X_tfidf.toarray())
print("Feature Names:", vectorizer_tfidf.get_feature_names_out())


TF-IDF Matrix:
[[0.         0.         0.37997836 0.         0.53404633 0.53404633
  0.53404633]
 [0.53404633 0.53404633 0.37997836 0.53404633 0.         0.
  0.        ]]
Feature Names: ['another' 'demonstration' 'example' 'for' 'is' 'simple' 'this']


In [46]:
from sklearn.feature_extraction.text import CountVectorizer

# Define the sentences
sentences = [
    "I like natural language processing.",
    "Natural language processing is fascinating."
]

# Create a CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the sentences to a Bag of Words representation
X = vectorizer.fit_transform(sentences)

# Convert the result to a dense matrix and display it as a DataFrame
import pandas as pd
bow_matrix = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
print(bow_matrix)


   fascinating  is  language  like  natural  processing
0            0   0         1     1        1           1
1            1   1         1     0        1           1


In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# Define the sentences
sentences = [
    "I like natural language processing.",
    "Natural language processing is fascinating."
]

# Create a TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the sentences to a TF-IDF representation
X = vectorizer.fit_transform(sentences)

# Convert the result to a dense matrix and display it as a DataFrame
tfidf_matrix = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
print(tfidf_matrix)


   fascinating        is  language      like   natural  processing
0     0.000000  0.000000  0.448321  0.630099  0.448321    0.448321
1     0.533098  0.533098  0.379303  0.000000  0.379303    0.379303


In [48]:
from sklearn.feature_extraction.text import CountVectorizer

# Define the sentences
sentences = [
    "I like natural language processing.",
    "Natural language processing is fascinating."
]

# Create a CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the sentences to a Bag of Words representation
X = vectorizer.fit_transform(sentences)

# Convert the result to a dense matrix and display it as a DataFrame
import pandas as pd
bow_matrix = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
print(bow_matrix)


   fascinating  is  language  like  natural  processing
0            0   0         1     1        1           1
1            1   1         1     0        1           1
